"""Admin_models

Revision ID: 982028706b89
Revises: 
Create Date: 2024-01-01 18:33:56.118537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '982028706b89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=30), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__user')),
                    sa.UniqueConstraint('id', name=op.f('uq__user__id')),
                    sa.UniqueConstraint('username', name=op.f('uq__user__username'))
                    )
    op.create_index(op.f('ix__user__email'), 'user', ['email'], unique=True)
    op.create_table('item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('item_name', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk__item__user_id__user')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__item')),
                    sa.UniqueConstraint('id', name=op.f('uq__item__id'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_index(op.f('ix__user__email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
