"""Admin_models

Revision ID: dd485f6b62df
Revises: 982028706b89
Create Date: 2024-01-02 00:50:41.518566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dd485f6b62df'
down_revision: Union[str, None] = '982028706b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__item__id'), 'item', ['id'])
    op.create_unique_constraint(op.f('uq__user__id'), 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__user__id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq__item__id'), 'item', type_='unique')
    # ### end Alembic commands ###
